### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [j-zero/orsala_hack#1]
Hello!

I found link to this project from https://hackaday.com/2021/02/17/custom-firmware-for-ikeas-orsala-lamp/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by newbrain** [comment]
I came here (from HaD) just to create the same license issue.
Without a license, we can only look at the code!

**Comment by j-zero** [comment]
License added.

**Comment by vazhnov** [comment]
BEERWARE — why not, it is better than nothing.
@j-zero , thank you!
