### ISSUE TITLE
Internal LED hardly visible

### ISSUE THREAD

**Issue by stan23** [j-zero/orsala_hack#5]
Just got a second hand Orsala after finding the post on hackaday and updated to your firmware.
I used the stock firmware only for less than an hour and have to admit that yours is indeed much better!

However I'm wondering about this internal LED. I didn't even notice it until I flashed the firmware and saw it flashing.
Is it supposed to be visible from the outside? There some kind of guide going to the top of the case, but in fact it just casts shadow.

Sure this is nothing that can be fixed through software, but I didn't find any other place to discuss.

**Comment by j-zero** [comment]
I too didn't notice the LED at first. I have no idea why it is there or if it even is used in the original firmware.
As you can see, I use the LED as debugging indicator for various things. But you can only see it if it's really dark.

**Comment by j-zero** [comment]
Maybe, the lamp socket design was changed, after the PCBs are made. It seems like a little to much effort, to place a surface mounted LED on the back of the PCB, under a hole just to not use it at the end.

**Comment by stan23** [comment]
Or the PCB came from a different project. 
Now seeing it in the dark it doesn't look like it was designed for this lamp and case. But it is great as an indicator to show that min or max is reached.

I'll check whether I can pull out or drill out that guide and insert something 3D-printed.

**Comment by j-zero** [comment]
I thought about drilling a hole and fill that with epoxy. Or something simple like that.
